services:
  - type: web
    name: WeatherWorld
    env: ruby
    plan: free
    buildCommand: "bundle install"
    startCommand: "bundle exec rackup config.ru -p $PORT"
    packages:
      - curl
      - libcurl4
      - libcurl4-openssl-dev
